### ISSUE TITLE
Issue with circle crop

### ISSUE THREAD

**Issue by Soklundy** [TakuSemba/CropMe#13] opened 2019-11-27 03:46 UTC
I have use app:cropme_overlay_shape="circle" but result is very zoom (Not the same with preview on crop screen)

**Comment by TakuSemba** [comment] 2019-11-27 04:06
Thank you for the report. I will check into it.

**Comment by lee-ngeap** [comment] 2019-11-27 12:06
Not only the circle, but also the rectangle.

**Comment by TakuSemba** [comment] 2019-11-27 14:29
Thank you for the reporting.

Unfortunately, I could not reproduce the issue on my environment.

It would be really appreciated if you could reproduce it on the demo app in this repo and provide me the branch, and if possible I want a gif or image of the unexpected cropped image with an explanation of how it should be.

**Comment by lee-ngeap** [comment] 2019-11-29 05:30
Anyways, your circle cropping is not right. The result not the same as in the preview while cropping. 
Please see attachment. Why the result is not circle, instead it's portrait? 

Result:
![kropme_circle](https://user-images.githubusercontent.com/29971302/69845727-2bfa9380-12a4-11ea-82ca-f4bf53e28d6a.jpg)

Result display on the mobile screen:
![tempFileForShare_20191129-123653](https://user-images.githubusercontent.com/29971302/69845988-205b9c80-12a5-11ea-9ea9-e9059d4769ed.jpg)

Suppose to display on the mobile screen as per previewing while cropping:
![tempFileForShare_20191129-123817](https://user-images.githubusercontent.com/29971302/69846011-38cbb700-12a5-11ea-8133-388eb5502368.jpg)

**Comment by lee-ngeap** [comment] 2019-11-29 05:34
Here is the original image. 
![20191129_093013](https://user-images.githubusercontent.com/29971302/69845821-8f84c100-12a4-11ea-8ca9-bc775ff51e38.jpg)

**Comment by lee-ngeap** [comment] 2019-11-29 05:50
This one for rectangle:
For the rectangle, the result is perfect. However, it's zoomed for the result display on the mobile.

Original:
![original](https://user-images.githubusercontent.com/29971302/69846478-b6dc8d80-12a6-11ea-9e2d-10802e4a8f85.jpg)

Result:
![result](https://user-images.githubusercontent.com/29971302/69846491-c065f580-12a6-11ea-8c22-44a0dbfbcb86.jpg)

Result display on the mobile screen:
![result display on the mobile](https://user-images.githubusercontent.com/29971302/69846500-c8be3080-12a6-11ea-941a-cc47a36f826c.jpg)

**Comment by TakuSemba** [comment] 2020-09-02 13:08
Unfortunately, I could not reproduce the issue.

Please report these details below so that I can look into it.
 - devices (this is device-specific? or happens on any device?)
 - Android OS version (this happens on any OS version or specific version?)
 - the original picture you tested.
 - screenshots on the demo app. (right before you crop / after you crop)

I'm closing this issue just for now.
Please reopen this with the detail information above, I am happy to help you.

**Closed as completed by TakuSemba** 2020-09-02 13:08 UTC
