### ISSUE TITLE
Crash On Samsung Device

### ISSUE THREAD

**Issue by kharelpankaj** [TakuSemba/CropMe#4] opened 2018-04-12 07:01 UTC
Whenever I call croperview.crop, I am getting this error in Samsung device. I have tested the same code with few more device , its working fine. 

FATAL EXCEPTION: main
                                                                          Process: PID: 1276
                                                                          java.lang.IllegalArgumentException: y + height must be <= bitmap.height()
                                                                              at android.graphics.Bitmap.createBitmap(Bitmap.java:829)
                                                                              at android.graphics.Bitmap.createBitmap(Bitmap.java:793)
                                                                              at com.takusemba.cropme.CropView.crop(CropView.java:240)
                                                                              at .Views.Activity.CropperActivity.onCrop(CropperActivity.java:44)
                                                                              at .Views.Activity.CropperActivity_ViewBinding$1.doClick(CropperActivity_ViewBinding.java:33)
                                                                              at butterknife.internal.DebouncingOnClickListener.onClick(DebouncingOnClickListener.java:22)
                                                                              at android.view.View.performClick(View.java:6205)
                                                                              at android.widget.TextView.performClick(TextView.java:11103)
                                                                              at android.view.View$PerformClick.run(View.java:23653)
                                                                              at android.os.Handler.handleCallback(Handler.java:751)
                                                                              at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                              at android.os.Looper.loop(Looper.java:154)
                                                                              at android.app.ActivityThread.main(ActivityThread.java:6682)
                                                                              at java.lang.reflect.Method.invoke(Native Method)
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)

**Comment by TakuSemba** [comment] 2018-05-29 04:58
sorry for the late replay.

i tested `GALAXY S5` and it worked fine.
what kind of device did you use?

**Comment by deepakrana0011** [comment] 2018-09-27 08:33
@TakuSemba this is not device specific issue. The problem is sometime image not cover the whole crop are in that case this issue occured

**Comment by es0329** [comment] 2018-12-07 18:27
I get the same Exception attempting to crop an image from the camera.
Images are successfully rendered only if they're selected from the device gallery.
This behavior seen using CropMe with the OnePlus 5T on stock Android version 8.1.0.

`implementation 'com.github.takusemba:cropme:1.1.0'`


```
FATAL EXCEPTION: Thread-5
Process: PID: 22330
java.lang.IllegalArgumentException: width and height must be > 0
at android.graphics.Bitmap.createBitmap(Bitmap.java:1013)
at android.graphics.Bitmap.createBitmap(Bitmap.java:980)
at android.graphics.Bitmap.createBitmap(Bitmap.java:930)
at android.graphics.Bitmap.createBitmap(Bitmap.java:851)
at android.graphics.Bitmap.createScaledBitmap(Bitmap.java:721)
at com.takusemba.cropme.CropLayout$4.run(CropLayout.java:171)
at java.lang.Thread.run(Thread.java:764)
```

**Comment by mondoktamas** [comment] 2019-04-19 10:44
I have this error if I move image out of frame and click to crop.

**Comment by TakuSemba** [comment] 2019-11-04 02:38
Can you check if the image is not off of the frame using CropLayout.isOffFrame()?

Also, can you check if this still happens on v2.0.0 which has just been released?

**Comment by TakuSemba** [comment] 2020-09-02 13:10
I'm closing this issue because I believe this is resolved adding `CropLayout.isOffFrame()` functionality.

**Closed as completed by TakuSemba** 2020-09-02 13:10 UTC
